# Generated by Django 2.0 on 2020-05-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0040_auto_20200514_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_reason_police', models.CharField(blank=True, default='No Reason given by Police', max_length=1000, null=True)),
                ('decline_reason_sho', models.CharField(blank=True, default='No Reason given by SHO', max_length=1000, null=True)),
                ('decline_reason_sp', models.CharField(blank=True, default='No Reason given by SP', max_length=1000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='caseclose',
            options={},
        ),
        migrations.AlterModelOptions(
            name='casestatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='copstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fir',
            options={},
        ),
        migrations.AddField(
            model_name='complaint',
            name='briefofoffence',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_police',
            field=models.CharField(blank=True, default='No Reason given by Police', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_sho',
            field=models.CharField(blank=True, default='No Reason given by SHO', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_sp',
            field=models.CharField(blank=True, default='No Reason given by SP', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='declinedstatus',
            field=models.CharField(choices=[('Declined by SHO', 'Declined by SHO'), ('Declined by SP', 'Declined by SP'), ('Declined by Police', 'Declined by Police'), ('Declined by no one', 'Declined by no one')], default='Declined by no one', max_length=25),
        ),
        migrations.AddField(
            model_name='complaint',
            name='digitalsignature',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameofcomplainant',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameofcriminal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='residenceofcomplainant',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='residenceofcriminal',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='signedstatus',
            field=models.CharField(choices=[('Signed by SHO', 'Signed by SHO'), ('Signed by SP', 'Signed by SP'), ('Signed by Police', 'Signed by Police'), ('Signed by Court', 'Signed by Court'), ('Signed by no one', 'Signed by no one')], default='Signed by no one', max_length=25),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='policestation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Complaint Registered', 'Complaint Registered'), ('FIR Filed', 'FIR Filed'), ('Complaint Under Progress', 'Complaint Under Progress'), ('Case Open', 'Case Open'), ('Case Closed', 'Case Closed')], default='Complaint Registered', max_length=30),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='content',
            field=models.CharField(blank=True, default='First Information Report not yet submitted', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='signedby',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
