# Generated by Django 2.0 on 2020-07-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0043_auto_20200515_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyAadharData',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('firt_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
                ('aadhar_no', models.CharField(blank=True, default='', max_length=12, null=True, unique=True)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoffacilitator', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fimage', models.ImageField(blank=True, default='', null=True, upload_to='fimages/')),
                ('faddress', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fphone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('femail', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('noofcasesassigned', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currentlyassigned', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='freport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitatorviews', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('facilitator_statement', models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='fstatements/')),
                ('f_evidence1', models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='f_evidences/')),
                ('f_evidence2', models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='f_evidences/')),
                ('f_evidence3', models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='f_evidences/')),
            ],
        ),
        migrations.CreateModel(
            name='Investigator_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofinvestigator', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('investigator_image', models.ImageField(blank=True, default='', null=True, upload_to='investigator_image/')),
                ('iaddress', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iphone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iemail', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('noofcasesassigned', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currentlyassigned', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='JSignatureModel',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='residenceofcomplainant',
            new_name='addressofcomplainant',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='briefofoffence',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='content',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='digitalsignature',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='nameofcriminal',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='policestation',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='residenceofcriminal',
        ),
        migrations.AddField(
            model_name='casestatus',
            name='evidence',
            field=models.FileField(blank=True, default='', null=True, upload_to='court_evidence/'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='title_of_update',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='aadharverification_status',
            field=models.CharField(choices=[('Aadhar Verified', 'Aadhar Verified'), ('Aadhar Not Verified', 'Aadhar Not Verified'), ('Skipped Aadhar Verification', 'Skipped Aadhar Verification')], default='Aadhar Not Verified', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='addressofsuspect',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='csignstatus',
            field=models.CharField(choices=[('Csign Added', 'Csign Added'), ('Csign Not Added', 'Csign Not Added')], default='Csign Not Added', max_length=25),
        ),
        migrations.AddField(
            model_name='complaint',
            name='datetimeofcrime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='descriptionofcrime',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='detailsofsuspect',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fassignstatus',
            field=models.CharField(choices=[('Facilitator Assigned', 'Facilitator Assigned'), ('Facilitator Not Assigned', 'Facilitator Not Assigned')], default='Facilitator Not Assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='firsignstatus',
            field=models.CharField(choices=[('Fir sign Added by Police', 'Fir sign Added by Police'), ('Fir sign Added by SHO', 'Fir sign Added by SHO'), ('Fir sign Added by SP', 'Fir sign Added by SP'), ('Fir sign Added by Court', 'Fir sign Added by Court'), ('Fir sign Not Added', 'Fir sign Not Added')], default='Fir sign Not Added', max_length=25),
        ),
        migrations.AddField(
            model_name='complaint',
            name='freport_status',
            field=models.CharField(choices=[('Facilitator Report Added', 'Facilitator Report Added'), ('Facilitator Report Not Added', 'Facilitator Report Not Added')], default='Facilitator Report Not Added', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='iassignstatus',
            field=models.CharField(choices=[('Investigator Assigned', 'Investigator Assigned'), ('Investigator Not Assigned', 'Investigator Not Assigned')], default='Investigator Not Assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigation_status',
            field=models.CharField(choices=[('Investigation Not Started', 'Investigation Not Started'), ('Investigation Started', 'Investigation Started'), ('Investigation Under Progress', 'Investigation Under Progress'), ('Investigation Done', 'Investigation Done')], default='Investigation Not Started', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='locationofcomplainantsign',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='locationofsketch',
            field=models.ImageField(blank=True, default='', null=True, upload_to='criminal_sketches/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameoffacilitator',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameofinvestigatorassigned',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameofsuspect',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nearestpolicestation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='payment',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='placeofincidence',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='roleofcomplainant',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sketchstatus',
            field=models.CharField(choices=[('Criminal Sketch Added', 'Criminal Sketch Added'), ('Criminal Sketch Not Added', 'Criminal Sketch Not Added'), ('Criminal Sketch Skipped', 'Criminal Sketch Skipped')], default='Criminal Sketch Not Added', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='typeofincidence',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='userstatement',
            field=models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='userstatements/'),
        ),
        migrations.AddField(
            model_name='copstatus',
            name='evidence',
            field=models.FileField(blank=True, default='', null=True, upload_to='police_evidence/'),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='courtname',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='dateofregister',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AddField(
            model_name='freport',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
