# Generated by Django 2.0 on 2020-05-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0046_auto_20200512_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_reason_police', models.CharField(blank=True, default='No Reason given by Police', max_length=1000, null=True)),
                ('decline_reason_sho', models.CharField(blank=True, default='No Reason given by SHO', max_length=1000, null=True)),
                ('decline_reason_sp', models.CharField(blank=True, default='No Reason given by SP', max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='decline_reason_police',
            field=models.CharField(blank=True, default='No Reason given by Police', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='decline_reason_sho',
            field=models.CharField(blank=True, default='No Reason given by SHO', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='decline_reason_sp',
            field=models.CharField(blank=True, default='No Reason given by SP', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AddField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
