# Generated by Django 2.0 on 2020-08-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0049_auto_20200801_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='c_evidence1',
            field=models.FileField(blank=True, default='', null=True, upload_to='c_evidences/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='c_evidence2',
            field=models.FileField(blank=True, default='', null=True, upload_to='c_evidences/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='c_evidence3',
            field=models.FileField(blank=True, default='', null=True, upload_to='c_evidences/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='c_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='c_video/'),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='freport',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
