# Generated by Django 2.0 on 2020-07-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0056_auto_20200711_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoffacilitator', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('faddress', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fphone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('femail', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('noofcasesassigned', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currentlyassigned', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
