# Generated by Django 2.0 on 2020-07-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0064_auto_20200714_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_police',
            field=models.CharField(blank=True, default='No Reason given by Police', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_sho',
            field=models.CharField(blank=True, default='No Reason given by SHO', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='decline_reason_sp',
            field=models.CharField(blank=True, default='No Reason given by SP', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='freport',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
