# Generated by Django 2.0 on 2020-07-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0065_auto_20200714_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofinvestigator', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('investigator_image', models.ImageField(blank=True, default='', null=True, upload_to='investigator_image/')),
                ('iaddress', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iphone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iemail', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('noofcasesassigned', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currentlyassigned', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='iassignstatus',
            field=models.CharField(choices=[('Investigator Assigned', 'Investigator Assigned'), ('Investigator Not Assigned', 'Investigator Not Assigned')], default='Investigator Not Assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigation_status',
            field=models.CharField(choices=[('Investigation Not Started', 'Investigation Not Started'), ('Investigation Started', 'Investigation Started'), ('Investigation Under Progress', 'Investigation Under Progress'), ('Investigation Done', 'Investigation Done')], default='Investigation Not Started', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='nameofinvestigatorassigned',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='freport',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
