# Generated by Django 2.0 on 2020-07-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0070_auto_20200722_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='m_aadharverification',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='m_filefir',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='m_sign',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sho_aadharverification',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sho_decline',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sho_filefir',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sho_sign',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sp_aadharverification',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sp_decline',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sp_filefir',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sp_sign',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='caseclose',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='copstatus',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='declinereason',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
        migrations.AlterField(
            model_name='freport',
            name='complaintid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
