# Generated by Django 2.0 on 2020-07-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStatus',
            new_name='Criminal_Info',
        ),
    ]
